### ISSUE TITLE
Release PR that supports .NETFramework v4.5

### ISSUE THREAD

**Issue by dhoer** [plecos/logrotatewin#12]
Is it possible to get the latest PR released which defaults to .NETFramework Version=v4.5?

**Comment by dhoer** [comment]
I have questions about 15 and 16 release mentioned in this thread: https://sourceforge.net/p/logrotatewin/discussion/general/thread/353f00f3/.  It looks like these changes are not reflected as commits to this repo.  Is that a correct assumption?  Also, only 14 release is out on sourceforge.

**Comment by plecos** [comment]
I am working to merge the changes and get an updated release of sourceforge...

**Comment by plecos** [comment]
Okay I have a pull request that has all of these changes in it.  Would you like to review it and if it works for you?

**Comment by dhoer** [comment]
I'm not really that familiar with Windows development.  I just have a requirement to rotate logs that are filling up disk on our Windows AWS machines.  I plan to write a Chef cookbook that will configure our Windows servers during provisioning, and it looks like yours best fits the bill. I appreciate you taking the time to do this.

**Comment by dhoer** [comment]
v0.0.0.17 released
