### ISSUE TITLE
Log file name issue

### ISSUE THREAD

**Issue by gomo** [plecos/logrotatewin#16]
Hi !

Thank you for making logrotatewin. I am saved.

I tried your logrotatewin and it works as expected, but the file name was different from my expectation.

Please see the screenshot.

<img width="389" alt="windows_10" src="https://user-images.githubusercontent.com/639604/27569387-4a0cda76-5b32-11e7-802a-0f7be097eb6d.png">

The number after the file name is irregular. Why does this happen?

I started logrotatewin at 5 o'clock in the morning at the Task Scheduler.

```
"C:\Program Files (x86)\Ken Salter\LogRotate\logrotate.exe" D:\logrotate\logrotate.conf
```

The contents of logrotate.conf are as follows.

```
"D:\log\**" {
	daily
	rotate 7
	missingok
	nocompress
	prerotate
		nssm stop selenium-server
        endscript
	postrotate
		nssm start selenium-server
        endscript
}
```

**Comment by plecos** [comment]
I think you need to change 

"D:\log\**" 

to 

"D:\log\*.log" 

With ** it is also processing the rotated files. 

Regards, 
Ken

**Comment by gomo** [comment]
> With ** it is also processing the rotated files.

Oh no! this is my shocking mistake :confounded:
Thanks.
