### ISSUE TITLE
My rotations are not working

### ISSUE THREAD

**Issue by oderayi** [plecos/logrotatewin#24]
Hello,

So, I installed logrotatewin, configured the logrotate.conf but the log files were never rotated.

Questions:
1. Is there any other step that I need to do after running the msi?
2. How do I check to know that logrotate is going to rotate? Is there a Scheduled Task entry or Windows Service entry installed anywhere on the server?

Thank you

**Comment by plecos** [comment]
No, there is no scheduled task or windows service. You will need to setup your own scheduled task once you are sure your config is good. So run logrotate from the command line to make sure it is working, then setup a scheduled task.

**Comment by oderayi** [comment]
Thank you @plecos 
Would be nice to update the wiki to capture that information.
Let me know if you need my help with that.
